FROM ghcr.io/graalvm/native-image:latest AS builder
RUN microdnf install -y findutils zip unzip

WORKDIR /app
COPY . .

RUN chmod +x ./gradlew \
    && ./gradlew nativeCompile --no-daemon -x test

FROM debian:bookworm-slim AS runtime
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/build/native/nativeCompile/oauthclient /app/oauthclient
RUN chmod +x /app/oauthclient

EXPOSE 8082

ENTRYPOINT ["/app/oauthclient"]